<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "registeraddress_categories"
 *
 * Auto generated by Extension Builder 2018-06-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Registeraddress Categories',
    'description' => 'Directmail category support for registeraddress',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
            'registeraddress' => '1.0.13',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
